[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = [
    "-C", "target-feature=+aes,+sse,+sse4.1,+sse4.2,+avx,+avx2,+prefetchwt1,+pclmul,+fma4,+fma,+bmi2,+bmi,+adx,+prefer-256-bit,+prefer-128-bit"
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
    "-C", "target-feature=+aes,+crypto,+neon",
]
