name: Build & Test

on: push
  #   branches: [master]
  # pull_request:
  #   branches: [master]

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: "-Ctarget-feature=+aes,+ssse3"

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/registry
  #           ~/.cargo/git
  #           target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #     - name: Build
  #       run: cargo build --features "aes-pmac-siv local-redir" --verbose
  #     - name: Run tests
  #       run: cargo test --features "aes-pmac-siv local-redir" --verbose

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/registry
  #           ~/.cargo/git
  #           target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #     - name: Build
  #       run: cargo build --features "aes-pmac-siv openssl-vendored" --verbose
  #     - name: Run tests
  #       run: cargo test --features "aes-pmac-siv openssl-vendored" --verbose

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-2
      - name: Build
        run: cargo build --features "aes-pmac-siv local-redir" --verbose
      - name: Run tests
        run: cargo test --features "aes-pmac-siv local-redir" --verbose
